blogproject/apps/api_url/urls.py
from django.urls import path,include
from api_view.views import ChangePasswordView,RegisterUserAPIView,PostAPIView, PostDetailAPIView , PostUpdateAPI ,UpdateAPI,PostCreateAPI,DeleteProfileAPI, UserLoginAPI,LogoutAPIView
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework.routers import DefaultRouter
from api_view.views import PostViewSet ,UserViewSet
from rest_framework.authtoken.views import obtain_auth_token  



schema_view = get_schema_view(
   openapi.Info(
      title="blogProject API",
      default_version='v1',
      description="User description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@xyz.com"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

def trigger_error(request):
    division_by_zero = 1 / 0

router = DefaultRouter()
router.register('post', PostViewSet,basename="post")
router.register('users', UserViewSet,basename="users")


urlpatterns = [
   path('post/', PostAPIView.as_view()),
   path('create/',PostCreateAPI.as_view()),
	path('<int:pk>/', PostDetailAPIView.as_view()),
   path('register/',RegisterUserAPIView.as_view()),
   path('login/',UserLoginAPI.as_view()),
   path('logout/',LogoutAPIView.as_view()),
   path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
   path('change-password/', ChangePasswordView.as_view()),
   path('password_reset/', include('django_rest_passwordreset.urls', namespace='password_reset')),
 #    path('update/<int:pk>/',UpdateAPI.as_view()),
 #    path('delete/',DeleteProfileAPI.as_view()),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('sentry/', trigger_error),
    path('', include(router.urls)),


    # path('postupdate',PostUpdateAPI.as_view()),
    # path('api-auth/', include('rest_framework.urls')),
    # path('api/v1/rest-auth/', include('rest_auth.urls'))
    # path('', views.send_mail, name='sendmail'),
    # path('<int:pk>/update/',PostAPIUpdate.as_view()),
    # path('<int:pk>/dalete/',PostAPIDelete.as_view()),
]

blogproject/apps/blog/urls.py
from django.urls import path
from .views import (BlogDetailView,BlogListView, BlogCreateView, BlogUpdateView, BlogDeleteView, ProfileView, BlogImage, SignUpView, ProfileUpdateView,add_comment)
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.models import User 
from . import views

app_name = 'blog'
urlpatterns = [
    # path('post/<int:pk>/delcmt/',views.delete_comment,name='delete-comment'),
    # path('post/<int:pk>/createcmt/',CommentView.as_view(),name='new_comment'),
    path('post/<int:pk>/like/', views.like_post, name='like_post'),
    path('post/<int:pk>/delete/',BlogDeleteView.as_view(),name='post_delete'),
    path('post/<int:pk>/edit/', BlogUpdateView.as_view(), name='post_edit'),
    path('post/new/', BlogCreateView.as_view(), name='post_new'),
    path('post/<int:pk>/post_detail',BlogDetailView.as_view(), name='post_detail'),
    path('',BlogListView.as_view(), name='home'),
    path('post/',BlogImage.as_view(),name='image'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/edit/<int:pk>',ProfileUpdateView.as_view(), name='profile_edit'),                                                                                                                                                                                                                   
    path('profile/',ProfileView.as_view(),name='profile'),
    path("post/comment/<int:pk>/",views.add_comment,name='comment'),
    path('sendmail/',views.sendMail,name='email'),
]   

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('django.contrib.auth.urls')),
    path('', include('blog.urls')),
    path('api/', include('api_url.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('accounts/', include('allauth.urls')),

    # path('social', include('social.apps.django_app.urls', namespace='social')),
    # path('api/v1/rest-auth/', include('rest_auth.urls'))
    
] 

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogproject/apps/blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone
from django.dispatch import receiver
from django_rest_passwordreset.signals import reset_password_token_created
from django.core.mail import send_mail
from django.conf import settings



class Post(models.Model):
    title = models.CharField(max_length=200)
    date = models.DateTimeField(default=timezone.now)
    header_image = models.ImageField(null=True, blank=True,upload_to="post_detail")
    author = models.ForeignKey('auth.User',related_name='posts',on_delete=models.CASCADE,)                                    
    body = models.TextField()
    likes = models.ManyToManyField(User,related_name="like",blank=True,default=None)
   
    def total_likes(self):
        return self.likes.all().count()
        
    def __str__(self):
        return self.title  

 
    def get_absolute_url(self):
        return reverse('blog:post_detail',args=[str(self.id)])

    @property
    def number_of_comments(self):
        return Comment.objects.filter(blogpost_connected=self).count()


    class Meta:
        ordering = ['-date']
   

class Comment(models.Model):
    author = models.ForeignKey('auth.User',on_delete=models.CASCADE,)
    content = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.content

    

@receiver(reset_password_token_created)
def password_reset_token_created(sender, instance, reset_password_token, *args, **kwargs):

    email_plaintext_message = "{}?token={}".format(reverse('password_reset:reset-password-request'), reset_password_token.key)

    send_mail(
        # title:
        "Password Reset for {title}".format(title="Some website title"),
        # message:
        email_plaintext_message,
        # from:
        "noreply@somehost.local",
        # to:
        [reset_password_token.user.email]
    )

blogproject/apps/blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Post
from .models import Comment


class blogForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'header_image', 'body']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author','content','created')


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','password1','password2']

 
class ProfileUpdateForm(forms.ModelForm):
    email =forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

class EmailForm(forms.Form):
    recipient = forms.EmailField()

blogproject/apps/api_view/views.py
from rest_framework import generics,permissions,status,viewsets
from blog.models import Post
from blog.serializer import RegisterSerializer,PostSerializer, LoginSerializer, UserProfileSerializer,UserSerializer,ChangePasswordSerializer
from django.core.mail import send_mail,EmailMessage
from django.shortcuts import render, HttpResponse
from django.conf import settings
from django.contrib.auth.models import User
from django.template import Context
from django.template.loader import render_to_string, get_template
from rest_framework.response import Response
from django.contrib.auth import login, authenticate,logout
from rest_framework.authtoken.serializers import AuthTokenSerializer
from rest_framework.permissions import IsAuthenticated,AllowAny,IsAdminUser
from rest_framework.authtoken.models import Token
from django.dispatch import receiver
from rest_framework.authentication import SessionAuthentication,TokenAuthentication
# from rest_framework.status import (
#     HTTP_400_BAD_REQUEST,
#     HTTP_404_NOT_FOUND,
#     HTTP_200_OK
# )


from rest_framework.generics import GenericAPIView
from rest_framework.decorators import action
# from blog.logs import exception,logger
from rest_framework import generics
from django.utils import timezone
import pytz
import datetime

class RegisterUserAPIView(generics.CreateAPIView):
    permission_classes = (AllowAny,)
    serializer_class = RegisterSerializer
    # @exception(logger)
    def post(self, request):
        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response({"data": serializer.data, "Message":"You are Successfully Registered"}, status=status.HTTP_200_OK)
        else:
            return Response({"Message":[serializer.errors]}, status=status.HTTP_400_BAD_REQUEST)


class PostViewSet(viewsets.ModelViewSet):

    queryset = Post.objects.all()
    serializer_class = PostSerializer
    permission_classes = [permissions.IsAuthenticated,]

    # @exception(logger)
    def perform_create(self, serializer):
        serializer.save(author=self.request.user)


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticated]
    

class UserLoginAPI(generics.CreateAPIView):
    serializer_class = LoginSerializer
    queryset = User.objects.all()

    # @exception(logger)
    def post(self, request, *args, **kwargs):
        username = request.data.get("username")
        password = request.data.get("password")
        if username is None or password is None:
            return Response({'error': 'Please provide both username and password'},
                            status=status.HTTP_400_BAD_REQUEST)
        user = authenticate(username=username, password=password)
        if not user:
            return Response({'error': 'Invalid Credentials'},
                            status=status.HTTP_404_NOT_FOUND)

        utc_now = timezone.now()
        utc_now = utc_now.replace(tzinfo = pytz.utc)
        token = Token.objects.filter(user=user, created__lt = utc_now - datetime.timedelta(seconds=30)).delete()
        token,create = Token.objects.get_or_create(user=user)
        token.save()
        token = str(token)
        data={
                "token":token,
                "username":username,
                }
        return Response({'data':data},status=status.HTTP_200_OK)


class LogoutAPIView(generics.DestroyAPIView):
    permission_classes = (permissions.IsAuthenticated,)
    authentication_classes = [TokenAuthentication]
    def get(self, request):
        Token.objects.filter(user=request.user).delete()
        logout(request)
        return Response({"message": "logout successfully", 'code': status.HTTP_200_OK,}) 


class UpdateAPI(generics.RetrieveUpdateAPIView):
    queryset = User.objects.all()
    serializer_class = UserProfileSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]


class DeleteProfileAPI(generics.DestroyAPIView):
    permission_classes = [permissions.IsAuthenticated]

    def delete(self, request, *args, **kwargs):
        Token.objects.filter(user=request.user).delete()
        user=self.request.user
        user.delete()

        return Response({"result":"user delete"})


class PostCreateAPI(generics.ListCreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    
    def perform_create(self, serializer):
        user = User.objects.get(id=self.request.user.id)
        user_email = user.email
        merge_data = {
            'greetings': "Hello"
         }
        html_message = get_template('blog/message.html').render(merge_data)
        from_email = settings.EMAIL_HOST_USER
        msg = EmailMessage('Hey Kuldeep !',
                   html_message,
                   from_email,
                  [user_email],
                 )
        msg.content_subtype ="html"
        msg.send()
        print("Mail successfully sent")

    
class PostAPIView(generics.ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer


class PostDetailAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]


class PostUpdateAPI(generics.UpdateAPIView):
    queryset = Post.objects.filter()
    serializer_class = PostSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]


class ChangePasswordView(generics.UpdateAPIView):
    """
    An endpoint for changing password.
    """
    serializer_class = ChangePasswordSerializer
    model = User
    permission_classes = (IsAuthenticated,)

    def get_object(self, queryset=None):
        obj = self.request.user
        return obj

    def update(self, request, *args, **kwargs):
        self.object = self.get_object()
        serializer = self.get_serializer(data=request.data)

        if serializer.is_valid():
            # Check old password
            if not self.object.check_password(serializer.data.get("old_password")):
                return Response({"old_password": ["Wrong password."]}, status=status.HTTP_400_BAD_REQUEST)
            # set_password also hashes the password that the user will get
            self.object.set_password(serializer.data.get("new_password"))
            self.object.save()
            response = {
                'status': 'success',
                'code': status.HTTP_200_OK,
                'message': 'Password updated successfully',
                'data': []
            }

            return Response(response)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
	

blogproject/templates/blog/comment_create.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>

<body>
    <button type="button" class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#myModal">Add comment</button> <span id="comment-count-{{post.pk}}">{{ post.comment_set.count }}</span>
<!-- List of comments -->
<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Comment Section</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>
            <div class="modal-body">
                <form action="#" method='POST' id="mainSubmit">
                    {% csrf_token %}
                    <textarea class="form-control" id="id_content" name="content" rows="4"></textarea>
                </form>
                <button type="submit" class=" btn btn-primary ml-2" id="submit-comment" form="mainSubmit" value="{{ post.pk }}">Comment</button>
            </div>
            {% if post.comment_set %}
            <div class="row mt-3">
                <div class="col-lg-8 offset-lg-3 ">
                    <strong>
                        <h2>Comment{{ comments.count }}</h2>
                    </strong>
                    <span class="badge badge-dark ml-2">{{ comments.count }}</span>
                </div>
                <div id='comments-{{ post.pk }}'>
                    {% for comment in post.comment.all %}
                    <div class="col-lg-6 offset-lg-3">
                        <div class="card p-2">
                            <div class="row">
                                <div class="col-12">
                                    <strong>{{ comment.author }}</strong>
                                </div>
                                <div class="col-12">
                                    <p class="m-1 mt-3">{{ comment.content }}</p>
                                    <p class="text-right text-muted"><small>{{ comment.created }}</small></p>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body>

</html>

blogproject/templates/blog/message.html
<!DOCTYPE html>
<htmllang="en">
  <head>
    <metacharset="UTF-8"/>
    <metaname="viewport"content="width=device-width, initial-scale=1.0"/>
    <title>Mail</title>
  </head>
  <body>
    Hello {{ user.username }},

    <p>Welcome to over site mini Instagram</p>
    <h1>Name - {{user.username}} </h1>
    <img src="{{emp.emp_image.url}}" alt="Smiley face" width="650" height="450">
    <br />
    <p>Thanks,</p>
  </body>
</html>

blogproject/templates/blog/post_delete.html
<center>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <h1><a style="color:pink">Instagram</a></h1>
  <a href="{% url 'blog:home' %}">Back to Home</a><br>
  <a  href="{% url 'logout' %}">Logout</a>
{% block content %}
  <h1>Delete post</h1>
  <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ post.title }}"?</p>
    <input type="submit" style="background-color:red" value="Confirm" />
  </form>
{% endblock content %}

blogproject/templates/blog/post_detail.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <center>
        <h1><a style="color:pink">Instagram</a></h1>
        <a href="{% url 'blog:home' %}">
            <h5>Home Page</h5>
        </a>
        <a href="{% url 'logout' %}">
            <h5>Logout</h5>
        </a>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>
<hr style="height:6px; width:100%; border-width:2;background-color:pink">
<p>
    <h3>{{ post.author }}</h3>
</p>
<h4>{{ post.title }}</h4>
<p>{{ post.body }}</p>
{% if post.header_image %}
    <img src="{{ post.header_image.url }}" width="500" />
{% endif %}
<p>{{ post.date }}</p>
<div class="btn-group btn-group-sm">
    <div id="like-section">
        {% include 'blog/postlikes.html' %}
    </div>
</div>
{% if user.username == post.author.username %}
<a href="{% url 'blog:post_edit' post.pk %}" class="btn btn-outline-info ">update</a>
<a href="{% url 'blog:post_delete' post.pk %}" class="btn btn-outline-danger">delete</a>
{% endif %}<br>
<div class="btn-group btn-group-sm">
    <div id="comments">
        {% include 'blog/comment_create.html' %}
    </div>
</div>
{% if post.comment_set %}
<h2>Comment{{ comments.count }}</h2>
{{ comments.count }}
<div id='comments-{{ post.pk }}'>
    {% for comment in post.comment.all %}
    <strong>{{ comment.author }}</strong>
    <p class="m-1 mt-3">{{ comment.content }}</p>
    <p class="text-right text-muted"><small>{{ comment.created }}</small></p>
    {% endfor %}
</div>
{% endif %}
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script src="{% static 'js/ajax.js' %}"></script>
</body>
</center>
</html>

blogproject/templates/blog/post_edit.html
<center>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  
  <h1><a style="color:pink">Instagram</a></h1>
<a href="{% url 'blog:home' %}">Back To Home</a><br>
    <a  href="{% url 'logout' %}">Logout</a>
{% block content %}
  <h1>Edit post</h1>
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
  <input class="btn btn-outline-info" type="submit" style="background-color:lightblue" value="Update" />
</form>
{% endblock content %}

blogproject/templates/blog/post_new.html
<center>
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <h1><a style="color:pink">Instagram</a></h1>
    <a href="{% url 'blog:home' %}">Back To Home</a><br>
    <a  href="{% url 'logout' %}">Logout</a>
{% block content %}
  {% if user.is_authenticated %}
   <h1>New post</h1>
   <form action="" method="post" enctype='multipart/form-data'>
      {{post.title}}
      {% csrf_token %}
      {{ form.media }}
      {{ form.as_p }}
      <input class="btn btn-outline-info" style=" background-color: #008CBA;" type="submit" value="Upload" />
   </form>
    {% endif %}
 
{% endblock content %}

blogproject/templates/blog/postlikes.html
{% block content %}
  <form  method="POST">
    <p id="total_likes-{{ post.pk }}">{{ post.total_likes }}</p>
   {% csrf_token %}
        {% if request.user in post.likes.all %}
            <button type="button" id="dislike-{{ post.pk }}" name="post_id" value="{{ post.pk }}" class="like-dislike btn btn-danger">Unlike</button>
        {% else %}
            <button type="button" id="like-{{ post.pk }}" name="post_id" value="{{ post.pk }}" class="like-dislike btn btn-primary">Like</button>
        {% endif %}
  </form>
{% endblock content %}

blogproject/templates/blog/profile.html
<center>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <h1><a style="color:pink">Instagram</a></h1>
     <a href="{% url 'blog:home' %}">Back To Home</a><br>
    <a  href="{% url 'logout' %}">Logout</a>
{% block title %}{{ post.title_tag }}{% endblock %}

{% block content %}
 <div class="content-section">
          <h2>Profile Detail</h2>
          <h4 class="account-heading">{{ user.username }}</h4>
          <h5 class='text-secondary'>{{user.first_name}} <br>{{user.last_name}}</h5>
          <p class="text-secondary">{{ user.email }}</p>
          <a href="{% url 'blog:profile_edit' user.pk %}"><button class="btn btn-outline-info" style="background-color:orange; border-color:black; color:white"> Edit Profile</button></a>
 </div>

  <form method="POST" >
    {% for post in object_list %}
         <div class='post-entry'>
            <h4>{{ post.author }}</h4>
            <h4><a href="{% url 'blog:post_detail' post.pk %}" style="color:lightgreen;">{{ post.title }}</a></h4>
            <h5>{{ post.body }}</h5>
            {% if post.header_image %}
              <h2><a href="{% url 'blog:post_detail' post.pk %}"><img src="{{ post.header_image.url }}" alt="" width="400" height="350">{{ form.media }}</img></a></h2>
            {% endif %} 
    {% endfor %}

  </form>

{% endblock content %}

blogproject/templates/blog/profile_edit.html
<center>
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  
  <h1><a style="color:pink">Instagram</a></h1>
  <a href="{% url 'blog:home' %}">Back To Home</a><br>
    <a  href="{% url 'logout' %}">Logout</a>
{% load crispy_forms_tags %}
{% block content %}
      <!-- FORM HERE -->
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4"> Edit Profile Info </legend>
              <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input class="btn btn-outline-info" style=" background-color: #008CBA;" type="submit" value="Update"/>
              </form>
        </fieldset>
    </form>

{% endblock content %}

blogproject/templates/blog/signup.html
<center>
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <h1><a style="color:pink">Instagram</a></h1>
{% if user.is_authenticated %}
  <a href="{% url 'home' %}"></a>
{% else %}
    {% block content %}
      <h2><a style='color:darkblue'> User Registration Page </a></h2>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-outline-info" type="submit" style=" background-color: gray;">Sign Up</button>
        <br><a href="{% url 'blog:home' %}">Back To Home</a><br>
      </form>
   {% endblock %}
{% endif %}