blogproject/apps/api_url/urls.py
from django.urls import path,include
from api_view.views import ChangePasswordView,RegisterUserAPIView,PostAPIView, PostDetailAPIView , PostUpdateAPI ,UpdateAPI,PostCreateAPI,DeleteProfileAPI, UserLoginAPI,LogoutAPIView
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework.routers import DefaultRouter
from api_view.views import PostViewSet ,UserViewSet
from rest_framework.authtoken.views import obtain_auth_token  



schema_view = get_schema_view(
   openapi.Info(
      title="blogProject API",
      default_version='v1',
      description="User description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@xyz.com"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)

def trigger_error(request):
    division_by_zero = 1 / 0

router = DefaultRouter()
router.register('post', PostViewSet,basename="post")
router.register('users', UserViewSet,basename="users")


urlpatterns = [
   path('post/', PostAPIView.as_view()),
   path('create/',PostCreateAPI.as_view()),
	path('<int:pk>/', PostDetailAPIView.as_view()),
   path('register/',RegisterUserAPIView.as_view()),
   path('login/',UserLoginAPI.as_view()),
   path('logout/',LogoutAPIView.as_view()),
   path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
   path('change-password/', ChangePasswordView.as_view()),
   path('password_reset/', include('django_rest_passwordreset.urls', namespace='password_reset')),
 #    path('update/<int:pk>/',UpdateAPI.as_view()),
 #    path('delete/',DeleteProfileAPI.as_view()),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('sentry/', trigger_error),
    path('', include(router.urls)),


    # path('postupdate',PostUpdateAPI.as_view()),
    # path('api-auth/', include('rest_framework.urls')),
    # path('api/v1/rest-auth/', include('rest_auth.urls'))
    # path('', views.send_mail, name='sendmail'),
    # path('<int:pk>/update/',PostAPIUpdate.as_view()),
    # path('<int:pk>/dalete/',PostAPIDelete.as_view()),
]

blogproject/apps/blog/urls.py
from django.urls import path
from .views import (BlogDetailView,BlogListView, BlogCreateView, BlogUpdateView, BlogDeleteView, ProfileView, BlogImage, SignUpView, ProfileUpdateView,add_comment)
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.models import User 
from . import views

app_name = 'blog'
urlpatterns = [
    # path('post/<int:pk>/delcmt/',views.delete_comment,name='delete-comment'),
    # path('post/<int:pk>/createcmt/',CommentView.as_view(),name='new_comment'),
    path('post/<int:pk>/like/', views.like_post, name='like_post'),
    path('post/<int:pk>/delete/',BlogDeleteView.as_view(),name='post_delete'),
    path('post/<int:pk>/edit/', BlogUpdateView.as_view(), name='post_edit'),
    path('post/new/', BlogCreateView.as_view(), name='post_new'),
    path('post/<int:pk>/post_detail',BlogDetailView.as_view(), name='post_detail'),
    path('',BlogListView.as_view(), name='home'),
    path('post/',BlogImage.as_view(),name='image'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('profile/edit/<int:pk>',ProfileUpdateView.as_view(), name='profile_edit'),                                                                                                                                                                                                                   
    path('profile/',ProfileView.as_view(),name='profile'),
    path("post/comment/<int:pk>/",views.add_comment,name='comment'),
    path('sendmail/',views.sendMail,name='email'),
]   

blogproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('django.contrib.auth.urls')),
    path('', include('blog.urls')),
    path('api/', include('api_url.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('accounts/', include('allauth.urls')),

    # path('social', include('social.apps.django_app.urls', namespace='social')),
    # path('api/v1/rest-auth/', include('rest_auth.urls'))
    
] 

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogproject/apps/blog/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Post
from .models import Comment


class blogForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'header_image', 'body']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author','content','created')


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','password1','password2']

 
class ProfileUpdateForm(forms.ModelForm):
    email =forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

class EmailForm(forms.Form):
    recipient = forms.EmailField()

blogproject/apps/api_view/views.py
from rest_framework import generics,permissions,status,viewsets
from blog.models import Post
from blog.serializer import RegisterSerializer,PostSerializer, LoginSerializer, UserProfileSerializer,UserSerializer,ChangePasswordSerializer
from django.core.mail import send_mail,EmailMessage
from django.shortcuts import render, HttpResponse
from django.conf import settings
from django.contrib.auth.models import User
from django.template import Context
from django.template.loader import render_to_string, get_template
from rest_framework.response import Response
from django.contrib.auth import login, authenticate,logout
from rest_framework.authtoken.serializers import AuthTokenSerializer
from rest_framework.permissions import IsAuthenticated,AllowAny,IsAdminUser
from rest_framework.authtoken.models import Token
from django.dispatch import receiver
from rest_framework.authentication import SessionAuthentication,TokenAuthentication
# from rest_framework.status import (
#     HTTP_400_BAD_REQUEST,
#     HTTP_404_NOT_FOUND,
#     HTTP_200_OK
# )


from rest_framework.generics import GenericAPIView
from rest_framework.decorators import action
# from blog.logs import exception,logger
from rest_framework import generics
from django.utils import timezone
import pytz
import datetime

class RegisterUserAPIView(generics.CreateAPIView):
    permission_classes = (AllowAny,)
    serializer_class = RegisterSerializer
    # @exception(logger)
    def post(self, request):
        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response({"data": serializer.data, "Message":"You are Successfully Registered"}, status=status.HTTP_200_OK)
        else:
            return Response({"Message":[serializer.errors]}, status=status.HTTP_400_BAD_REQUEST)


class PostViewSet(viewsets.ModelViewSet):

    queryset = Post.objects.all()
    serializer_class = PostSerializer
    permission_classes = [permissions.IsAuthenticated,]

    # @exception(logger)
    def perform_create(self, serializer):
        serializer.save(author=self.request.user)


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticated]
    

class UserLoginAPI(generics.CreateAPIView):
    serializer_class = LoginSerializer
    queryset = User.objects.all()

    # @exception(logger)
    def post(self, request, *args, **kwargs):
        username = request.data.get("username")
        password = request.data.get("password")
        if username is None or password is None:
            return Response({'error': 'Please provide both username and password'},
                            status=status.HTTP_400_BAD_REQUEST)
        user = authenticate(username=username, password=password)
        if not user:
            return Response({'error': 'Invalid Credentials'},
                            status=status.HTTP_404_NOT_FOUND)

        utc_now = timezone.now()
        utc_now = utc_now.replace(tzinfo = pytz.utc)
        token = Token.objects.filter(user=user, created__lt = utc_now - datetime.timedelta(seconds=30)).delete()
        token,create = Token.objects.get_or_create(user=user)
        token.save()
        token = str(token)
        data={
                "token":token,
                "username":username,
                }
        return Response({'data':data},status=status.HTTP_200_OK)


class LogoutAPIView(generics.DestroyAPIView):
    permission_classes = (permissions.IsAuthenticated,)
    authentication_classes = [TokenAuthentication]
    def get(self, request):
        Token.objects.filter(user=request.user).delete()
        logout(request)
        return Response({"message": "logout successfully", 'code': status.HTTP_200_OK,}) 


class UpdateAPI(generics.RetrieveUpdateAPIView):
    queryset = User.objects.all()
    serializer_class = UserProfileSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]


class DeleteProfileAPI(generics.DestroyAPIView):
    permission_classes = [permissions.IsAuthenticated]

    def delete(self, request, *args, **kwargs):
        Token.objects.filter(user=request.user).delete()
        user=self.request.user
        user.delete()

        return Response({"result":"user delete"})


class PostCreateAPI(generics.ListCreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    
    def perform_create(self, serializer):
        user = User.objects.get(id=self.request.user.id)
        user_email = user.email
        merge_data = {
            'greetings': "Hello"
         }
        html_message = get_template('blog/message.html').render(merge_data)
        from_email = settings.EMAIL_HOST_USER
        msg = EmailMessage('Hey Kuldeep !',
                   html_message,
                   from_email,
                  [user_email],
                 )
        msg.content_subtype ="html"
        msg.send()
        print("Mail successfully sent")

    
class PostAPIView(generics.ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer


class PostDetailAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]


class PostUpdateAPI(generics.UpdateAPIView):
    queryset = Post.objects.filter()
    serializer_class = PostSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]


class ChangePasswordView(generics.UpdateAPIView):
    """
    An endpoint for changing password.
    """
    serializer_class = ChangePasswordSerializer
    model = User
    permission_classes = (IsAuthenticated,)

    def get_object(self, queryset=None):
        obj = self.request.user
        return obj

    def update(self, request, *args, **kwargs):
        self.object = self.get_object()
        serializer = self.get_serializer(data=request.data)

        if serializer.is_valid():
            # Check old password
            if not self.object.check_password(serializer.data.get("old_password")):
                return Response({"old_password": ["Wrong password."]}, status=status.HTTP_400_BAD_REQUEST)
            # set_password also hashes the password that the user will get
            self.object.set_password(serializer.data.get("new_password"))
            self.object.save()
            response = {
                'status': 'success',
                'code': status.HTTP_200_OK,
                'message': 'Password updated successfully',
                'data': []
            }

            return Response(response)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
	

blogproject/apps/blog/views.py
from django.views.generic import ListView, DetailView , View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy,reverse
from .models import Post,Comment
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordChangeView
from .forms import CommentForm,UserRegisterForm, ProfileUpdateForm,EmailForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from rest_framework import generics
from django.core.mail import send_mail
# from rest_framework.authtoken.views import ObtainAuthToken


# def token(request):
#     return render(request,"token.html", {'token_apikey': settings.TOKEN_APIKEY, 'environment': settings.ENVIRONMENT})

# def genrate_token(request):
#     endpoint = f"{settings.BASE_URL}get_auth_token"
#     data = {"username": "admin009", "password": "asdf@123"}
#     response = requests.request("POST", endpoint, data=data).json()
#     return JsonResponse(response)


# class CustomObtainAuthToken(ObtainAuthToken):
#     def post(self, request, *args, **kwargs):
#         response = super(CustomObtainAuthToken, self).post(request, *args, **kwargs)
#         token = Token.objects.get(key=response.data['token'])
#         league_id = UserProfile.objects.get(pk=token.user_id)
#         user = UserProfile.objects.get(pk=token.user_id)
#         return Response({'token': token.key, 'user_id': token.user_id, 'first_name': user.first_name, 'last_name': user.last_name,})


class ProfileUpdateView(UpdateView):
    form_class = ProfileUpdateForm
    queryset = User.objects.all()
    template_name = 'blog/profile_edit.html'
    success_url = reverse_lazy('blog:profile')


class ProfileView(ListView):
    model = Post
    template_name='blog/profile.html'

    def get_queryset(self):
        author_id = self.request.user
        return Post.objects.filter(author=author_id).order_by("date")


class SignUpView(CreateView):
    form_class = UserRegisterForm
    success_url = reverse_lazy('login')
    template_name = 'blog/signup.html'


class BlogListView(ListView):
    model = Post
    template_name = 'home.html'
    


class BlogDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'


    
def add_comment(request, *args, **kwargs):
        objs = Post.objects.filter(id=kwargs['pk'])[0]
        obj = objs.comment_set.create(author=request.user, content=request.POST.get('content'))
        response = {
            'user': obj.author.username,
            'content': obj.content,
            'post': obj.post.id,
            'created': obj.created,
            'count': objs.comment_set.count()
        }
        return JsonResponse(response)


class BlogCreateView(CreateView,LoginRequiredMixin):
    model = Post
    template_name = 'blog/post_new.html'
    fields = ['title','header_image','body']
    

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Post
    template_name = 'blog/post_edit.html'
    fields = ['title','header_image', 'body']


class BlogDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy("blog:home")
    template_name = 'blog/post_delete.html'
    
    
class BlogImage(ListView):
    model = Post
    template_name = 'blog/post_detail.html'


@login_required
def like_post(request,pk): 
    if request.method == "POST":
        post = get_object_or_404(Post,id=request.POST.get('post_id',pk))
        id=pk
        is_liked=False
        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user.id)
            is_liked=False
        else:
            post.likes.add(request.user.id)
            is_liked=True            

        total_dict={'total_likes':post.total_likes(),'is_liked':is_liked}

        return JsonResponse(total_dict)

def sendMail(request):
    if request.method == 'POST':
        form = EmailForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            subject = "Sending an for successful Regitering to our site"
            message = "Wel COme to our website you are a Successfully user for our site Enjoy."
            send_mail(subject, message,
                      settings.DEFAULT_FROM_EMAIL, [cd['recipient']])
    return render(request, 'homepage.html')



    

blogproject/templates/base.html
<html lang='en'>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>
<center>
<body>
  <div class='container'>
    <div class='py-5 text-center bg-secondary text-white'>
      <header>
        <div class="nav-left">
           <span class="border border-secondry"></span>
           <h2> Home Page </h2>
           <h1><a style="color:pink">Instagram</a></h1>
        </div>
      </header>
      {% if user.is_authenticated %}
      <h2>Hello {{ user.username }} !</h2>
        <a href="{% url 'blog:profile' %}"><button class="btn btn-outline-info" style="background-color:blue;  color:white" > Profile Page </button></a><br><br>

        <a href="{% url 'blog:home' %}"><button class="btn btn-outline-info" style="background-color:green; border-color:black; color:white">Home</button></a>

        <a href="{% url 'blog:post_new' %}"><button class="btn btn-outline-info" style="background-color:orange; border-color:black; color:white">Create Post</button></a>

        <a  href="{% url 'logout' %}"><button class="btn btn-outline-info" style="background-color:red; border-color:black; color:white">Logout</button></a><br><br>

      {% else %}
        <p>You are not logged In</p>
        <a href="{% url 'login' %}"><button class="btn btn-outline-info" style="background-color:#008CBA;color:white">Login</button></a>
        <a href="{% url 'blog:signup' %}"><button class="btn btn-outline-info" style="background-color:gray;color:white" >Signup</button></a>
      {% endif %}
     {% block content %}
     {% endblock content %}
    </div> 
  </div>
</body>
</center>
</html>

blogproject/templates/header_image.html
<!DOCTYPE html>
<html lang='en'>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>image upload example</title>
</head>
<body>
  <form method = 'post' enctype='multipart/form-data'>
    {% csrf_token %}
    {{ form.as_p }}
    <button type='submit'>Upload</button>
    {% if img_obj %}
  <h3>Succesfully uploaded : {{img_obj.title}}</h3>
  <img src="{{ img_obj.image.url}}" alt="connect" style="max-height:300px">
  <img src="{{ form.media }}" alt="connect" style="max-height:300px">
{% endif %}
  </form>
</body>
</html>

blogproject/templates/header_image_display.html
{% load static %}
<!DOCTYPE html>
<html>
<body>
    <h1>Name - {{emp.name}} </h1>
    <img src="{{emp.emp_image.url}}" alt="Smiley face" width="650" height="450">
    <br />
    <a href="{% url 'home' %}">Go Back!!!</a>
</body>
</html>

blogproject/templates/home.html
{% extends 'base.html' %} {% load static %}
{% block content %}
<html>
<hr style="height:6px; width:100%; border-width:2;background-color:white" >
<body>
    {% if user.is_authenticated %}
        {% for post in object_list %}

            <div class='post-entry'>
                <h4>{{ post.author }}</h4>
                <h2><a href="{% url 'blog:post_detail' post.pk %}" style="color:black;">{{ post.title }}</a></h2>            
                <p>{{ post.body }}</p>
                {% if post.header_image %}
                  <h2><a href="{% url 'blog:post_detail' post.pk %}"><img src="{{ post.header_image.url }}" alt="" width="400" height="350">{{ form.media }}</img></a></h2>
                {% endif %} 
                <h6>{{ post.date }}</h6>
            </div>
            
              <form method="POST">
               {% csrf_token %}
                    <p id="total_likes-{{ post.pk }}">{{ post.total_likes }}</p>
                    {% if request.user in post.likes.all %}
                        <button type="button" id="dislike-{{ post.pk }}" name="post_id" value="{{ post.pk }}" class="like-dislike btn btn-danger">Unlike</button>
                    {% else %}
                        <button type="button" id="like-{{ post.pk }}" name="post_id" value="{{ post.pk }}" class="like-dislike btn btn-primary">Like</button>
                    {% endif %}
              </form>
        <hr style="height:3px; width:100%; border-width:2;background-color:pink" >
        {% endfor %}
    {% endif %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
 
<script src="{% static 'js/ajax.js' %}"></script>
</body>
</html>
{% endblock content %}